### ISSUE TITLE
Crashes if yaml file contains only a comment

### ISSUE THREAD

**Issue by OmegaLambda1998** [JuliaData/YAML.jl#129]
Given the yaml file:
```
# Test
```

The following code crashes:
```
using YAML
open("test.yaml", "r") do io
    YAML.load(io)
end
```

With the error:
```
ERROR: AssertionError: typeof(forward!(composer.input)) == DocumentStartEvent
Stacktrace:
  [1] compose_document(composer::YAML.Composer)
    @ YAML ~/.julia/packages/YAML/78yP9/src/composer.jl:49
  [2] compose(events::YAML.EventStream)
    @ YAML ~/.julia/packages/YAML/78yP9/src/composer.jl:38
  [3] load(ts::YAML.TokenStream, constructor::YAML.Constructor)
    @ YAML ~/.julia/packages/YAML/78yP9/src/YAML.jl:38
  [4] load(ts::YAML.TokenStream, more_constructors::Nothing, multi_constructors::Dict{Any, Any}; dicttype::Type{Dict{Any, Any}}, constructorType::typeof(YAML.SafeConstructor))
    @ YAML ~/.julia/packages/YAML/78yP9/src/YAML.jl:44
  [5] load
    @ ~/.julia/packages/YAML/78yP9/src/YAML.jl:44 [inlined]
  [6] #load#10
    @ ~/.julia/packages/YAML/78yP9/src/YAML.jl:47 [inlined]
  [7] load (repeats 3 times)
    @ ~/.julia/packages/YAML/78yP9/src/YAML.jl:47 [inlined]
  [8] #load#13
    @ ~/.julia/packages/YAML/78yP9/src/YAML.jl:88 [inlined]
  [9] load(::String)
    @ YAML ~/.julia/packages/YAML/78yP9/src/YAML.jl:88
 [10] top-level scope
    @ REPL[7]:1
```

You can get an even quicker crash via:
```
YAML.load("#")
```

**Comment by OmegaLambda1998** [comment]
I'd expect this to return an empty dictionary, rather than crashing

**Comment by kescobo** [comment]
It's valid YAML according to https://www.yamllint.com/

**Comment by Paalon** [comment]
Result from [YPaste Interactive Parser](http://ben-kiki.org/ypaste).

![スクリーンショット 2024-06-03 19 50 07](https://github.com/JuliaData/YAML.jl/assets/11065457/da817ce2-2800-419a-9468-804e33bdbbb8)

I think this should not return an empty dictionary because it's different.
![スクリーンショット 2024-06-03 19 52 45](https://github.com/JuliaData/YAML.jl/assets/11065457/7258c895-2c6b-400f-9218-a0c66b089d08)

**Comment by Paalon** [comment]
This YAML file `#` represents no document (0 documents).

**Comment by Paalon** [comment]
This is not a bug for the same reason as #143.

**Comment by GunnarFarneback** [comment]
This crash was never intentional. #219 fixed it to return `nothing`. Returning an empty dictionary is indeed not an option.
