### ISSUE TITLE
Should warn about unknown directives

### ISSUE THREAD

**Issue by Paalon** [JuliaData/YAML.jl#148]
According to https://yaml.org/spec/1.2.2/, 6.8.,
> A YAML [processor](https://yaml.org/spec/1.2.2/#processes-and-models) should ignore unknown directives with an appropriate warning.

and the reserved directives are `YAML` and `TAG` but the following does not warn:

```julia
julia> YAML.load("""%FOO  bar baz\n\n--- foo""")
"foo"
```

**Comment by kescobo** [comment]
Thank you for opening all these issues! Just a heads up - to my knowledge, no one is actively developing this package. I'm trying to classify things and add my 2c where I have them, and I'm happy to review PRs when I can, but if you'd like these things addressed in any reasonable amount of time, I'm afraid you'll have to work on it yourself :-/
