### ISSUE TITLE
Git automatically converts EOL newlines

### ISSUE THREAD

**Issue by Paalon** [JuliaData/YAML.jl#216]
Git convert EOL newlines for operating systems perhaps in default. For easy debugging and testing, ~we should prohibit it by setting~.

Complement: it was misleading, I want to say, we should be explicit whether CRLF or LF for input YAML files of our tests.

**Comment by GunnarFarneback** [comment]
I'm not so sure about that since it would increase the risk that we fail to find Windows specific problems during testing and that they turn up in the wild instead.

**Comment by Paalon** [comment]
Then, we'll just add tests for the CRLF version of all LF tests.

**Comment by GunnarFarneback** [comment]
That doesn't sound like a good idea for DRY reasons. I think Windows CI is good enough to capture problems but if we want to run CRLF tests on Linux/Mac, the way to do that is to create CRLF versions of the files on the fly while running the tests.

**Comment by kescobo** [comment]
related to #232

**Comment by GunnarFarneback** [comment]
> the way to do that is to create CRLF versions of the files on the fly while running the tests.

Implemented in #235.
