### ISSUE TITLE
Move to JuliaData organization?

### ISSUE THREAD

**Issue by kescobo** [JuliaData/YAML.jl#83]
See also #62 and https://github.com/BioJulia/BufferedStreams.jl/issues/61#issuecomment-624236569

@quinnj suggested he's into the idea. In https://github.com/BioJulia/BufferedStreams.jl/issues/61#issuecomment-624236569, @BenJWard suggested he's open to moving this out of BioJulia. Is there any reason not to?

**Comment by quinnj** [comment]
Happy to facilitate the move by giving someone w/ admin powers here admin powers at JuliaData to make the move (alternatively, someone could give me temporary admin powers to BioJulia to make the move; I promise I won't destroy anything!)

**Comment by kescobo** [comment]
I have admin powers on this repo, and Ben said he's in favor of the move over on Slack. If you don't mind giving me whatever privileges I need to initiate the transfer, I can take care of it today. 

Is anything else required in terms of the General registry?

**Comment by quinnj** [comment]
Ok, I invited you to JuliaData, so you should be able to transfer the repo now. In General, it's just a matter of changing the url to point here, but github will redirect in the mean time. Also, you probably want to take a look over the docs/README in case some urls need to be changed there also.

**Comment by kescobo** [comment]
#84 🎉
